name: "HA X-Ray core"
description: "Homeassistant X-Ray core container"
version: "0.0.4"
slug: "ha_xray_core"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  beer: true
  wine: true
  liquor: false
  name: "world"
  year: 2017
schema:
  beer: bool
  wine: bool
  liquor: bool
  name: str
  year: int