name: "HA X-Ray core"
description: "Homeassistant X-Ray core container"
version: "0.0.8"
slug: "ha_xray_core"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
# options:
#   bridges:
#     - domain: example.com
#       local: "127.0.0.1:80"
#       portal:
#         address: "portal's IP address"
#         port: 1234
#         user_id: "5783a3e7-e373-51cd-8642-c83782b807c5"
#       in_tag: in_bridge
#       out_tag: out_bridge
# schema:
#   bridges:
#     - domain: str
#       local: str
#       portal:
#         address: str
#         port: port
#         user_id: str
#       in_tag: str
#       out_tag: str
